services:
  uvx-mcpo:
    container_name: mcpo
    build: .
    volumes:
      - ./mcp-config.json:/config.json:ro
    ports:
      - "8000:8000"
    restart: unless-stopped
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /data/openweb-ui:/app/backend/data
    restart: unless-stopped
    env_file:
      - .env-open-webui
    env:
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
