services:
  uvx-mcpo:
    build: .
    volume:
      - ./mcp-config.json:/opt/mcp-config.json:ro
    ports:
      - "8000:8000"
    command: uvx mcpo --port 8000 -- uvx mcp-server-time --local-timezone=America/Sao_Paulo -- config /opt/mcp-config.json
